### ISSUE TITLE
Site doesn't load on my network

### ISSUE THREAD

**Issue by bicycleghost** [ekzhang/setwithfriends#141]
Since last week the site doesn't load on my network. Tried using different browsers and different devices to no avail. It's stuck on the loading animation and the api requests keep failing. I tried clearing the site data, disabled all extensions.

It seems this request keeps getting ERR_CONNECTION_TIMED_OUT
`https://setwithfriends.firebaseio.com/.lp?start=t&ser=71983043&cb=3&v=5&p=1:970544876139:web:06295fe4079007f76abf2e`

And I also see this in the console:
`WebSocket connection to 'wss://socket.arc.io/socketcluster/?nodeId=XEQ52B9fFYahLxpYaHpGaQ' failed: WebSocket is closed before the connection is established.`

**Comment by ekzhang** [comment]
For the first error message: Is your ISP blocking outbound connections to `firebaseio.com`, or are you in a country (e.g., Iran) where Google refuses service due to legal reasons?

The second error message is not a problem, since Arc is just an ancillary provider. But the fact that the request to `socket.arc.io` is being blocked indicates a larger issue with your network. Are there any other sites on the Internet that you have noticed recently stopped working for you?

**Comment by bicycleghost** [comment]
Didn't have this problem on any other site  As far as I know, nothing is blocked by my ISP, so no idea that the issue was. Anyways, I tried again now and it now finally loads. Thanks for the help. We can close the issue now :)
