### ISSUE TITLE
game does not end

### ISSUE THREAD

**Issue by mathmil** [ekzhang/setwithfriends#160]
[This](https://setwithfriends.com/game/best-fearless-town) game does not end, despite no more SETs being visible.

**Comment by ekzhang** [comment]
Thanks, I've fixed the database state for this game.

This can happen if there's a game that finishes while none of its players remain on the site. Since you're not in the game when you're viewing, there's a case that prevents the `finishGame` handler from being called if you're not actually a player, just a spectator.

I guess this doesn't really make sense in hindsight, so I'll remove this conditional.
