### ISSUE TITLE
Unable to start a new game "FirebaseError: deadline-exceeded"

### ISSUE THREAD

**Issue by pe5ha** [ekzhang/setwithfriends#175]
A new game is not created from the computer (firefox browser) and an error occurs: "FirebaseError: deadline-exceeded"

A new game is not created from the phone (chrome browser) and an error occurs: "FirebaseError: internal"

Everything was working yesterday

**Comment by ekzhang** [comment]
Interesting. It happens "one out of every 200 games" according to the community meeting today. Will investigate.

**Comment by ekzhang** [comment]
Unfortunately this is kind of hard to reproduce. There are a couple possibilities:

- Timeout on the client
- Timeout on the function (60s)
- Network error

I guess we could add retries to the client but it seems that it only affects a very small percentage of games. For now going to mark as resolved.

It's also possible upgrading to Cloud Functions v2 would fix this, since that's a more modern serverless platform and they might have fixed some reliability issues on their side. I don't want to do this right now though since for some reason they have no direct migration path, you have to delete the old functions, take down your site for several minutes, then redeploy with the code changes. :/
