### ISSUE TITLE
Kicking system

### ISSUE THREAD

**Issue by DaNooob** [ekzhang/setwithfriends#4]
It would be useful to kick someone from a room because some people make programs to solve the game and ruins it for others. Also remove the "<button style="display: none;">Cheat</button> button" from the method for it.

**Comment by ekzhang** [comment]
Hi @DaNooob, thank you for the suggestions. About kicking users: I would suggest that you simply do not share your invitation link to users who do not act in good faith. The application should be secure in the sense that game IDs are private and randomly generated, so users won't be able to join unless you share the link. While a "kick" feature might be nice, it's not really technically useful at present because someone can just clear their cache with a hard refresh and rejoin with a new anonymous account -- and I value people being able to easily join games without a login.

As for the "cheat button", this is useful for debugging, and I'm assuming good faith. However, I can understand that it makes it much more technically easier for people to act dishonestly. I'll remove it in the next release.
