### ISSUE TITLE
Feature request: draw 3

### ISSUE THREAD

**Issue by cgbuen** [ekzhang/setwithfriends#48]
Great implementation! I've been waiting for something like this!

I've got the card game rulebook in hand which reads:

> If all players agree that there is not a set in the 12 cards, 3 more cards are laid face up on the table.

I thought it might be a cool feature to have maybe something like a "raise hand to draw" button so that when all players have clicked it, a "draw 3" scenario is triggered. This is good for when there is an available set on the board but no active player can find it.

**Comment by ekzhang** [comment]
Thanks @cgbuen, this is a common suggestion. I'm keeping this issue here in case anyone wants to work on it - it'd likely be within a separate mode, as in #37.

**Comment by maksverver** [comment]
Since the server already solves the "there is no set on the table" problem by adding cards, the remaining "the players don't see a set" problem could also be solved by providing a hint to unblock the players.

A hint could be triggered either by a timeout (e.g. 1 minute) or by all players clicking a "hint" button (similar to Christopher's suggestion). The first hint could reveal one card from a set, the second hint two, the third hint three. Of course the later hints are very spoiler-y but at least this would unblock the players.

**Comment by ekzhang** [comment]
@maksverver Thanks for your input. We actually just recently implemented a hint feature (#66), and it will be released soon.

**Comment by maksverver** [comment]
The hint feature described there sounds a bit different, but maybe I misunderstood. I'll wait for the next release and try it out!

**Comment by ekzhang** [comment]
Closing this, as I think we're probably going to keep the current interface that adds cards automatically as-is for now.
