### ISSUE TITLE
Unable to Access the Site from Iran

### ISSUE THREAD

**Issue by BehEsMo** [ekzhang/setwithfriends#74]
Hi. 
I live in Iran and was looking forward to play the wonderful Game of Set with my friends, using your excellent implementation. Unfortunately, it was not possible, because some of us couldn't access the site. I found out that It can only be accessed using a VPN app (and thus, changing the IP). I'm not sure, but maybe some IP's have been restricted from connecting to the site. 
I would be grateful if this problem could be resolved.

P.S. I'm pretty sure that It's not restricted by the Iranian government.

**Comment by ekzhang** [comment]
Hi @BehEsMo, I'm sorry to hear that you can't access the site. Is it possible to share what error you're getting when you try to access the site? Please screenshot what you see and describe any error messages, as access could be being blocked at a number of different parts of the system. This way we can hopefully figure out the root cause and resolve it.

If possible, also open the Google Chrome JavaScript console (press `F12 key` on your keyboard) on setwithfriends.com and screenshot that as well.

**Comment by BehEsMo** [comment]
Thanks, @ekzhang. These are screenshots of the errors I encountered while trying to access the site (using two different devices connected to two different ISP's) and the Google Chrome JavaScript console screenshots as you instructed (when using a VPN, and otherwise):

![Set With Friends Windows](https://user-images.githubusercontent.com/78323953/106516281-0ee6d380-64ec-11eb-9cc2-d19d2a927d86.JPG)

![ab06abeb-01fc-4988-8071-7c08da0e85aa](https://user-images.githubusercontent.com/78323953/106516825-ddbad300-64ec-11eb-85ef-e9751ff15157.jpg)

![Set With Friends WindowsJS](https://user-images.githubusercontent.com/78323953/106516156-e4951600-64eb-11eb-903f-474e52a00dd4.JPG)

![Set With Friends WindowsJS2](https://user-images.githubusercontent.com/78323953/106517019-270b2280-64ed-11eb-9893-41a9ee7ac6a2.JPG)

**Comment by ekzhang** [comment]
Thanks for the detailed information @BehEsMo. I did a bit of research based on the problems you're seeing, and the issue is that Netlify (our site hosting provider) has some parts of its infrastructure hosted on Google, [which unfortunately blocks connections from Iran due to US trade restrictions](https://community.netlify.com/t/using-netlify-in-iran-custom-domain-only-works-with-vpn/1380). This is out of our control, and I'm very sad that the site doesn't work for you. 😞 

Hopefully the bigger actors here will be kind enough to lift this IP blocking, but as of right now I can't do much.

**Comment by BehEsMo** [comment]
Dear @ekzhang, I appreciate your effort and kindness.❤️
Cruel U.S. sanctions hurt the Iranian people in so many ways, from hardship in providing some medicines to playing "Set with Friends". :|
I just can hope someday you use a site hosting provider not obeying the inhumane restrictions of the U.S. government on the Iranian people.
