### ISSUE TITLE
Proposing alternate game mode "Superset"

### ISSUE THREAD

**Issue by TungE** [ekzhang/setwithfriends#81]
Now that infrastructure for alternate game modes has been built, it may not be overly difficult to add other variants of Set, such as Superset. Superset can simply be described as Set but with an additional characteristic (e.g. give each card a border with one of three colors).

**Comment by ekzhang** [comment]
Bump, is this still being worked on?

**Comment by TungE** [comment]
Yes, I apologize for the inactivity as I've been preoccupied recently. I'm interested in this feature but I'm not sure how to develop for it because it requires some backend changes. Is there a way I can test the backend changes as I develop?

**Comment by ekzhang** [comment]
Yes, we can add you as an editor on the Firebase staging server. Are you on the [Discord server](https://discord.com/invite/XbjJyc9)? Please send me your Google account email, and I can get you access.

**Comment by NilsEnevoldsen** [comment]
A few comments:

1. I recommend a different name, as SuperSet already has a well-accepted meaning. Perhaps "5-dimensional SET", "3^5 SET", or "243 SET". (I also recommend changing the name of this issue for clarity.)
2. Note that the deck size will triple to 243, and since 5d sets are harder to find, game length will almost certainly more than triple. I suspect this game mode will not actually be _fun_, but I haven't tried it. Has anyone tried this mode before?
3. The board will have to expand.
   1. In 3^4 SET, the initial board of 12 [has 2.8 sets on average](https://www.wolframalpha.com/input/?i=%2812+choose+3%29+*+1%2F79) and 3% probability of no sets. As the game goes on, these odds worsen (fewer sets on average, higher probability of no sets). The worst possible board (cap set) is 20 cards (or 21 since it's dealt in 3s).
   2. In 3^5 SET, the initial board should have more than 2.8 sets on average, since they are harder to find. I would start with playtesting 20, [which has 4.7 sets on average](https://www.wolframalpha.com/input/?i=%2820+choose+3%29+*+1%2F241). (I don't know the the probability of no sets.) [The cap set is 45 cards](https://oeis.org/A090245). I think you would want to add more than 3 cards at a time. Perhaps 5?
4. I _have_ printed a deck and played with "4^3 SET", which worked okay, but the original "3^4 SET" is more fun.

**Comment by NilsEnevoldsen** [comment]
[Board game manuals Wiki](https://boardgamemanuals.fandom.com/wiki/Set_(game)) calls the variant "Mega-Set" and suggests 15-16 cards initially.

**Comment by ekzhang** [comment]
Closing because we're not going to add this new feature at this time.

**Comment by ekzhang** [comment]
For context: This was added to [@eltoder's fork](https://github.com/eltoder/setwithfriends/pull/84) so you can play there if you're curious what this is like

**Comment by NilsEnevoldsen** [comment]
Here is my deck, made in Paint in 2003. I don't know if there's a common name for "4^3 SET".

![Image](https://github.com/user-attachments/assets/88a1abd3-96b8-45b5-8549-a87007304963)

**Comment by eltoder** [comment]
@NilsEnevoldsen thank you! And the rule for sets was: 4 cards such that on every trait they are either all the same, all different, or 2 pairs?

**Comment by NilsEnevoldsen** [comment]
IIRC, I only played with the rule "4 cards such that on every trait they are either all the same or all different".

"Pairs" is an interesting idea to make it more playable though.

I think I only played a few hours total.

**Comment by eltoder** [comment]
I believe without pairs you won't get the property that for every three cards there's a unique fourth one that makes a set with them.

**Comment by NilsEnevoldsen** [comment]
That's true. I don't think that property is essential for gameplay though. But it might improve the game rhythm.

**Comment by eltoder** [comment]
@NilsEnevoldsen looking further into it, without pairs there are just too few sets, so you need a lot of cards on the board.

If you're interested to see how it works with pairs, we have both 4^3 and 4^4 on the fork: https://setwithforks-dev.web.app/
